#!/usr/bin/env python
from misc.utility.scons_hints import *

import subprocess
import sys

from methods import print_warning

Import("env")

openharmony_files = [Glob("*.cpp")]

env_openharmony = env.Clone()

openharmony_objects = []
for x in openharmony_files:
    openharmony_objects.append(env_openharmony.SharedObject(x))

lib_arch_dir = ""
if env["arch"] == "arm64":
    lib_arch_dir = "arm64-v8a"
elif env["arch"] == "x86_64":
    lib_arch_dir = "x86_64"
else:
    print_warning("Architecture not suitable for embedding into APP; keeping .so at \\bin")

#lib = env_openharmony.add_shared_library("#bin/libgodot", [openharmony_objects], SHLIBSUFFIX=env["SHLIBSUFFIX"])
lib = env_openharmony.add_shared_library(f"#platform/openharmony/template/entry/src/main/cpp/libs/{lib_arch_dir}/libgodot", [openharmony_objects], SHLIBSUFFIX=".so")
env.Command("#platform/openharmony/template/entry/src/main/cpp/include/bridge_openharmony.h", "#platform/openharmony/bridge_openharmony.h", Copy('$TARGET', '$SOURCE'))